[package]
name = "rust_transformers"
version = "0.1.0"
authors = ["Guillaume B <guillaume.becquin@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.1"
unicode-normalization = "0.1.8"
rayon = "1.2.1"
lazy_static = "1.4.0"
itertools = "0.8.2"
tch = { git = "https://github.com/LaurentMazare/tch-rs" , rev = "97bb47ee00c17371c1c9d163939e236a491068c8"}

[dependencies.pyo3]
version = "0.8.3"
features = ["extension-module"]

[dev-dependencies]
tempfile = "3.1.0"

[lib]
name = "rust_transformers"
path = "src/lib.rs"
crate-type = ["lib", "cdylib"]

[[bin]]
name = "rust_transformers_bin"
path = "src/main.rs"